function createfigure_alignedMaxProj(cdata1, cdata2)
%CREATEFIGURE(cdata1, cdata2)
%  CDATA1:  image cdata
%  CDATA2:  image cdata

%  Auto-generated by MATLAB on 02-Oct-2019 10:52:12

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create image
image(cdata1,'Parent',subplot1);

% Create title
title('un-aligned');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 640.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 480.5]);
box(subplot1,'on');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'Layer','top');
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create image
image(cdata2,'Parent',subplot2);

% Create title
title('aligned');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.5 640.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.5 480.5]);
box(subplot2,'on');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'Layer','top');
